{% set name = "records" %}
{% set version = "0.5.3" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "47e4874096f4a8f4b5bcad8c7c7cf512be36186e6e263ff3dfd750b05ff0d3c4" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  entry_points:
    - records = records:cli
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - sqlalchemy
    - tablib
    - docopt
    - pandas

test:
  imports:
    - records

  commands:
    - records --help

about:
  home: https://github.com/kennethreitz/records
  license_file: LICENSE
  license: ISC
  license_family: OTHER
  summary: 'SQL for Humans'
  dev_url: https://github.com/kennethreitz/records

extra:
  recipe-maintainers:
    - pmlandwehr
