{% set name = "records" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 320265b94ae87ca5d22643811aa199ce8a8c50d50064053b1a9a54e6ae565d9f

build:
  noarch: python
  entry_points:
    - records = records:cli
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sqlalchemy >=2.0
    - tablib >=0.11.4
    - openpyxl >2.6.0
    - docopt

test:
  imports:
    - records

  commands:
    - records --help
    - pip check

  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kennethreitz/records
  license_file: LICENSE
  license: ISC
  license_family: OTHER
  summary: 'SQL for Humans'
  dev_url: https://github.com/kennethreitz/records

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
